-- schema_config INSERTs for source_name = 'HubSpot'  (REGENERATED for review)
-- landing_column_name = full JSON source path (nav tokens $/__parent__ stripped), '.'->'_' , case preserved
-- bronze_column_name  = last real path segment, lowercased+snake; parent prepended only on collision
-- silver_column_name and all other fields = UNCHANGED from current statements
-- Rows for tables without a JSON file, and rows whose silver has no JSON source, are LEFT AS-IS.

-- [marketing_events]  (9 transformed / 18 kept)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'marketing_events', 'object_id', 'STRING', 'marketing_events_base_temp', 'marketing_event_id', 'STRING', 'marketing_events_temp', 'marketing_event_id', 'STRING', 1, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'externalEventId', 'STRING', 'marketing_events_base_temp', 'external_event_id', 'STRING', 'marketing_events_temp', 'external_event_id', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'eventName', 'STRING', 'marketing_events_base_temp', 'event_name', 'STRING', 'marketing_events_temp', 'event_name', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'eventType', 'STRING', 'marketing_events_base_temp', 'event_type', 'STRING', 'marketing_events_temp', 'event_type', 'STRING', 4, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'eventStatus', 'STRING', 'marketing_events_base_temp', 'event_status', 'STRING', 'marketing_events_temp', 'event_status', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'eventStatusV2', 'STRING', 'marketing_events_base_temp', 'event_status_v2', 'STRING', 'marketing_events_temp', 'event_status_v2', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'start_date_time', 'STRING', 'marketing_events_base_temp', 'start_timestamp', 'STRING', 'marketing_events_temp', 'start_timestamp', 'STRING', 7, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'end_date_time', 'STRING', 'marketing_events_base_temp', 'end_timestamp', 'STRING', 'marketing_events_temp', 'end_timestamp', 'STRING', 8, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'event_organizer', 'STRING', 'marketing_events_base_temp', 'event_organizer_email', 'STRING', 'marketing_events_temp', 'event_organizer_email', 'STRING', 9, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'eventDescription', 'STRING', 'marketing_events_base_temp', 'event_description', 'STRING', 'marketing_events_temp', 'event_description', 'STRING', 10, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'eventUrl', 'STRING', 'marketing_events_base_temp', 'event_url', 'STRING', 'marketing_events_temp', 'event_url', 'STRING', 11, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'event_cancelled', 'STRING', 'marketing_events_base_temp', 'is_cancelled', 'STRING', 'marketing_events_temp', 'is_cancelled', 'INT', 12, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'event_completed', 'STRING', 'marketing_events_base_temp', 'is_completed', 'STRING', 'marketing_events_temp', 'is_completed', 'INT', 13, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'registrants', 'STRING', 'marketing_events_base_temp', 'registrants_count', 'STRING', 'marketing_events_temp', 'registrants_count', 'INT', 14, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'attendees', 'STRING', 'marketing_events_base_temp', 'attendees_count', 'STRING', 'marketing_events_temp', 'attendees_count', 'INT', 15, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'cancellations', 'STRING', 'marketing_events_base_temp', 'cancellations_count', 'STRING', 'marketing_events_temp', 'cancellations_count', 'INT', 16, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'no_shows', 'STRING', 'marketing_events_base_temp', 'no_shows_count', 'STRING', 'marketing_events_temp', 'no_shows_count', 'INT', 17, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'appInfo_id', 'STRING', 'marketing_events_base_temp', 'id', 'STRING', 'marketing_events_temp', 'app_info_id', 'STRING', 18, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'appInfo_name', 'STRING', 'marketing_events_base_temp', 'name', 'STRING', 'marketing_events_temp', 'app_info_name', 'STRING', 19, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'created_at', 'STRING', 'marketing_events_base_temp', 'created_timestamp', 'STRING', 'marketing_events_temp', 'created_timestamp', 'STRING', 20, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_events', 'updated_at', 'STRING', 'marketing_events_base_temp', 'updated_timestamp', 'STRING', 'marketing_events_temp', 'updated_timestamp', 'STRING', 21, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [marketing_emails]  (28 transformed / 48 kept)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'marketing_emails', 'id', 'STRING', 'marketing_emails_base_temp', 'marketing_email_id', 'STRING', 'marketing_emails_temp', 'marketing_email_id', 'STRING', 1, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'name', 'STRING', 'marketing_emails_base_temp', 'marketing_email_name', 'STRING', 'marketing_emails_temp', 'marketing_email_name', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'subject', 'STRING', 'marketing_emails_base_temp', 'email_subject', 'STRING', 'marketing_emails_temp', 'email_subject', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'state', 'STRING', 'marketing_emails_base_temp', 'email_state', 'STRING', 'marketing_emails_temp', 'email_state', 'STRING', 4, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'type', 'STRING', 'marketing_emails_base_temp', 'email_type', 'STRING', 'marketing_emails_temp', 'email_type', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'subcategory', 'STRING', 'marketing_emails_base_temp', 'email_subcategory', 'STRING', 'marketing_emails_temp', 'email_subcategory', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'language', 'STRING', 'marketing_emails_base_temp', 'email_language', 'STRING', 'marketing_emails_temp', 'email_language', 'STRING', 7, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'archived', 'STRING', 'marketing_emails_base_temp', 'is_archived', 'STRING', 'marketing_emails_temp', 'is_archived', 'INT', 8, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'is_ab', 'STRING', 'marketing_emails_base_temp', 'is_ab_test', 'STRING', 'marketing_emails_temp', 'is_ab_test', 'INT', 9, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'isPublished', 'STRING', 'marketing_emails_base_temp', 'is_published', 'STRING', 'marketing_emails_temp', 'is_published', 'INT', 10, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'isTransactional', 'STRING', 'marketing_emails_base_temp', 'is_transactional', 'STRING', 'marketing_emails_temp', 'is_transactional', 'INT', 11, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'send_on_publish', 'STRING', 'marketing_emails_base_temp', 'is_send_on_publish', 'STRING', 'marketing_emails_temp', 'is_send_on_publish', 'INT', 12, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'jitter_send_time', 'STRING', 'marketing_emails_base_temp', 'is_jitter_send_time', 'STRING', 'marketing_emails_temp', 'is_jitter_send_time', 'INT', 13, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'activeDomain', 'STRING', 'marketing_emails_base_temp', 'active_domain', 'STRING', 'marketing_emails_temp', 'active_domain', 'STRING', 14, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'campaign', 'STRING', 'marketing_emails_base_temp', 'campaign_id', 'STRING', 'marketing_emails_temp', 'campaign_id', 'STRING', 15, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'campaignName', 'STRING', 'marketing_emails_base_temp', 'campaign_name', 'STRING', 'marketing_emails_temp', 'campaign_name', 'STRING', 16, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'campaignUtm', 'STRING', 'marketing_emails_base_temp', 'campaign_utm', 'STRING', 'marketing_emails_temp', 'campaign_utm', 'STRING', 17, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'emailCampaignGroupId', 'STRING', 'marketing_emails_base_temp', 'email_campaign_group_id', 'STRING', 'marketing_emails_temp', 'email_campaign_group_id', 'STRING', 18, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'primaryEmailCampaignId', 'STRING', 'marketing_emails_base_temp', 'primary_email_campaign_id', 'STRING', 'marketing_emails_temp', 'primary_email_campaign_id', 'STRING', 19, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'emailTemplateMode', 'STRING', 'marketing_emails_base_temp', 'email_template_mode', 'STRING', 'marketing_emails_temp', 'email_template_mode', 'STRING', 20, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'feedbackSurveyId', 'STRING', 'marketing_emails_base_temp', 'feedback_survey_id', 'STRING', 'marketing_emails_temp', 'feedback_survey_id', 'STRING', 21, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'folderId', 'STRING', 'marketing_emails_base_temp', 'folder_id', 'STRING', 'marketing_emails_temp', 'folder_id', 'STRING', 22, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'businessUnitId', 'STRING', 'marketing_emails_base_temp', 'business_unit_id', 'STRING', 'marketing_emails_temp', 'business_unit_id', 'STRING', 23, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'cloned_from', 'STRING', 'marketing_emails_base_temp', 'cloned_from_email_id', 'STRING', 'marketing_emails_temp', 'cloned_from_email_id', 'STRING', 24, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'previewKey', 'STRING', 'marketing_emails_base_temp', 'preview_key', 'STRING', 'marketing_emails_temp', 'preview_key', 'STRING', 25, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'publish_date', 'STRING', 'marketing_emails_base_temp', 'publish_timestamp', 'STRING', 'marketing_emails_temp', 'publish_timestamp', 'STRING', 26, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'published_at', 'STRING', 'marketing_emails_base_temp', 'published_timestamp', 'STRING', 'marketing_emails_temp', 'published_timestamp', 'STRING', 27, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'unpublished_at', 'STRING', 'marketing_emails_base_temp', 'unpublished_timestamp', 'STRING', 'marketing_emails_temp', 'unpublished_timestamp', 'STRING', 28, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'publishedByEmail', 'STRING', 'marketing_emails_base_temp', 'published_by_email', 'STRING', 'marketing_emails_temp', 'published_by_email', 'STRING', 29, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'published_by_id', 'STRING', 'marketing_emails_base_temp', 'published_by_user_id', 'STRING', 'marketing_emails_temp', 'published_by_user_id', 'STRING', 30, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'publishedByName', 'STRING', 'marketing_emails_base_temp', 'published_by_name', 'STRING', 'marketing_emails_temp', 'published_by_name', 'STRING', 31, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'created_at', 'STRING', 'marketing_emails_base_temp', 'created_timestamp', 'STRING', 'marketing_emails_temp', 'created_timestamp', 'STRING', 32, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'created_by_id', 'STRING', 'marketing_emails_base_temp', 'created_by_user_id', 'STRING', 'marketing_emails_temp', 'created_by_user_id', 'STRING', 33, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'deleted_at', 'STRING', 'marketing_emails_base_temp', 'deleted_timestamp', 'STRING', 'marketing_emails_temp', 'deleted_timestamp', 'STRING', 34, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'updated_at', 'STRING', 'marketing_emails_base_temp', 'updated_timestamp', 'STRING', 'marketing_emails_temp', 'updated_timestamp', 'STRING', 35, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'updated_by_id', 'STRING', 'marketing_emails_base_temp', 'updated_by_user_id', 'STRING', 'marketing_emails_temp', 'updated_by_user_id', 'STRING', 36, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'from_fromName', 'STRING', 'marketing_emails_base_temp', 'from_name', 'STRING', 'marketing_emails_temp', 'from_name', 'STRING', 37, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'from_reply_to', 'STRING', 'marketing_emails_base_temp', 'from_reply_to_email', 'STRING', 'marketing_emails_temp', 'from_reply_to_email', 'STRING', 38, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'from_custom_reply_to', 'STRING', 'marketing_emails_base_temp', 'from_custom_reply_to_email', 'STRING', 'marketing_emails_temp', 'from_custom_reply_to_email', 'STRING', 39, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'subscriptionDetails_subscriptionId', 'STRING', 'marketing_emails_base_temp', 'subscription_id', 'STRING', 'marketing_emails_temp', 'subscription_id', 'STRING', 40, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'subscriptionDetails_subscriptionName', 'STRING', 'marketing_emails_base_temp', 'subscription_name', 'STRING', 'marketing_emails_temp', 'subscription_name', 'STRING', 41, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'subscriptionDetails_officeLocationId', 'STRING', 'marketing_emails_base_temp', 'office_location_id', 'STRING', 'marketing_emails_temp', 'subscription_office_location_id', 'STRING', 42, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'subscriptionDetails_preferencesGroupId', 'STRING', 'marketing_emails_base_temp', 'preferences_group_id', 'STRING', 'marketing_emails_temp', 'subscription_preferences_group_id', 'STRING', 43, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'webversion_url', 'STRING', 'marketing_emails_base_temp', 'url', 'STRING', 'marketing_emails_temp', 'webversion_url', 'STRING', 44, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'webversion_enabled', 'STRING', 'marketing_emails_base_temp', 'is_webversion_enabled', 'STRING', 'marketing_emails_temp', 'is_webversion_enabled', 'INT', 45, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'content', 'STRING', 'marketing_emails_base_temp', 'content', 'STRING', 'marketing_emails_temp', 'content_json', 'STRING', 46, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'stats', 'STRING', 'marketing_emails_base_temp', 'stats', 'STRING', 'marketing_emails_temp', 'stats_json', 'STRING', 47, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'testing', 'STRING', 'marketing_emails_base_temp', 'testing', 'STRING', 'marketing_emails_temp', 'testing_json', 'STRING', 48, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'rssData', 'STRING', 'marketing_emails_base_temp', 'rss_data', 'STRING', 'marketing_emails_temp', 'rss_data_json', 'STRING', 49, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'to', 'STRING', 'marketing_emails_base_temp', 'to', 'STRING', 'marketing_emails_temp', 'to_json', 'STRING', 50, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'allEmailCampaignIds', 'STRING', 'marketing_emails_base_temp', 'all_email_campaign_ids', 'STRING', 'marketing_emails_temp', 'all_email_campaign_ids_json', 'STRING', 51, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'teamsWithAccess', 'STRING', 'marketing_emails_base_temp', 'teams_with_access', 'STRING', 'marketing_emails_temp', 'teams_with_access_json', 'STRING', 52, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'workflowNames', 'STRING', 'marketing_emails_base_temp', 'workflow_names', 'STRING', 'marketing_emails_temp', 'workflow_names_json', 'STRING', 53, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'content_json_templatePath', 'STRING', 'marketing_emails_base_temp', 'content_template_path', 'STRING', 'marketing_emails_temp', 'content_template_path', 'STRING', 54, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'content_json_widgets', 'STRING', 'marketing_emails_base_temp', 'content_widgets_json', 'STRING', 'marketing_emails_temp', 'content_widgets_json', 'STRING', 55, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'content_json_flexAreas', 'STRING', 'marketing_emails_base_temp', 'content_flex_areas_json', 'STRING', 'marketing_emails_temp', 'content_flex_areas_json', 'STRING', 56, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'content_json_styleSettings', 'STRING', 'marketing_emails_base_temp', 'content_style_settings_json', 'STRING', 'marketing_emails_temp', 'content_style_settings_json', 'STRING', 57, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'testing_json_abSampleSizeDefault', 'STRING', 'marketing_emails_base_temp', 'ab_sample_size_default', 'STRING', 'marketing_emails_temp', 'ab_sample_size_default', 'STRING', 58, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'testing_json_abSamplingDefault', 'STRING', 'marketing_emails_base_temp', 'ab_sampling_default', 'STRING', 'marketing_emails_temp', 'ab_sampling_default', 'STRING', 59, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'testing_json_abStatus', 'STRING', 'marketing_emails_base_temp', 'ab_status', 'STRING', 'marketing_emails_temp', 'ab_status', 'STRING', 60, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'testing_json_abSuccessMetric', 'STRING', 'marketing_emails_base_temp', 'ab_success_metric', 'STRING', 'marketing_emails_temp', 'ab_success_metric', 'STRING', 61, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'testing_json_abTestPercentage', 'STRING', 'marketing_emails_base_temp', 'ab_test_percentage', 'STRING', 'marketing_emails_temp', 'ab_test_percentage', 'INT', 62, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'testing_json_hoursToWait', 'STRING', 'marketing_emails_base_temp', 'ab_hours_to_wait', 'STRING', 'marketing_emails_temp', 'ab_hours_to_wait', 'INT', 63, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'testing_json_isAbVariation', 'STRING', 'marketing_emails_base_temp', 'is_ab_variation', 'STRING', 'marketing_emails_temp', 'is_ab_variation', 'INT', 64, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'testing_json_testId', 'STRING', 'marketing_emails_base_temp', 'ab_test_id', 'STRING', 'marketing_emails_temp', 'ab_test_id', 'STRING', 65, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'to_json_suppressGraymail', 'STRING', 'marketing_emails_base_temp', 'is_suppress_graymail', 'STRING', 'marketing_emails_temp', 'is_suppress_graymail', 'INT', 66, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'to_json_contactIds', 'STRING', 'marketing_emails_base_temp', 'to_contact_ids_json', 'STRING', 'marketing_emails_temp', 'to_contact_ids_json', 'STRING', 67, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'to_json_contactIlsLists', 'STRING', 'marketing_emails_base_temp', 'to_contact_ils_lists_json', 'STRING', 'marketing_emails_temp', 'to_contact_ils_lists_json', 'STRING', 68, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'to_json_contactLists', 'STRING', 'marketing_emails_base_temp', 'to_contact_lists_json', 'STRING', 'marketing_emails_temp', 'to_contact_lists_json', 'STRING', 69, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_emails', 'to_json_limitSendFrequency', 'STRING', 'marketing_emails_base_temp', 'is_limit_send_frequency', 'STRING', 'marketing_emails_temp', 'is_limit_send_frequency', 'INT', 70, 1, 0, 0, '0', 1, GETUTCDATE());

-- [event_types]  (no JSON file)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'event_types', 'event_type', 'STRING', 'event_types_base_temp', 'event_type_code', 'STRING', 'event_types_temp', 'event_type_code', 'STRING', 1, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [crm_contacts]  (24 transformed / 0 kept)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_contacts', 'id', 'STRING', 'crm_contacts_base_temp', 'id', 'STRING', 'crm_contacts_temp', 'id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'createdAt', 'STRING', 'crm_contacts_base_temp', 'created_at', 'STRING', 'crm_contacts_temp', 'created_at', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'updatedAt', 'STRING', 'crm_contacts_base_temp', 'updated_at', 'STRING', 'crm_contacts_temp', 'updated_at', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'archived', 'STRING', 'crm_contacts_base_temp', 'archived', 'STRING', 'crm_contacts_temp', 'archived', 'BOOLEAN', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'url', 'STRING', 'crm_contacts_base_temp', 'url', 'STRING', 'crm_contacts_temp', 'url', 'STRING', 5, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_agent_id__c', 'STRING', 'crm_contacts_base_temp', 'agent_id__c', 'STRING', 'crm_contacts_temp', 'agent_id_c', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_agent_number', 'STRING', 'crm_contacts_base_temp', 'agent_number', 'STRING', 'crm_contacts_temp', 'agent_number', 'STRING', 7, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_associatedcompanyid', 'STRING', 'crm_contacts_base_temp', 'associatedcompanyid', 'STRING', 'crm_contacts_temp', 'associatedcompanyid', 'STRING', 8, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_associatedcompanylastupdated', 'STRING', 'crm_contacts_base_temp', 'associatedcompanylastupdated', 'STRING', 'crm_contacts_temp', 'associatedcompanylastupdated', 'STRING', 9, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_company', 'STRING', 'crm_contacts_base_temp', 'company', 'STRING', 'crm_contacts_temp', 'company', 'STRING', 10, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_createdate', 'STRING', 'crm_contacts_base_temp', 'createdate', 'STRING', 'crm_contacts_temp', 'createdate', 'STRING', 11, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_email', 'STRING', 'crm_contacts_base_temp', 'email', 'STRING', 'crm_contacts_temp', 'email', 'STRING', 12, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_hs_email_click', 'STRING', 'crm_contacts_base_temp', 'hs_email_click', 'STRING', 'crm_contacts_temp', 'hs_email_click', 'STRING', 13, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_hs_email_first_click_date', 'STRING', 'crm_contacts_base_temp', 'hs_email_first_click_date', 'STRING', 'crm_contacts_temp', 'hs_email_first_click_date', 'STRING', 14, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_hs_email_first_open_date', 'STRING', 'crm_contacts_base_temp', 'hs_email_first_open_date', 'STRING', 'crm_contacts_temp', 'hs_email_first_open_date', 'STRING', 15, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_hs_email_first_reply_date', 'STRING', 'crm_contacts_base_temp', 'hs_email_first_reply_date', 'STRING', 'crm_contacts_temp', 'hs_email_first_reply_date', 'STRING', 16, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_hs_email_first_send_date', 'STRING', 'crm_contacts_base_temp', 'hs_email_first_send_date', 'STRING', 'crm_contacts_temp', 'hs_email_first_send_date', 'STRING', 17, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_hs_email_last_click_date', 'STRING', 'crm_contacts_base_temp', 'hs_email_last_click_date', 'STRING', 'crm_contacts_temp', 'hs_email_last_click_date', 'STRING', 18, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_hs_email_last_email_name', 'STRING', 'crm_contacts_base_temp', 'hs_email_last_email_name', 'STRING', 'crm_contacts_temp', 'hs_email_last_email_name', 'STRING', 19, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_hs_email_last_open_date', 'STRING', 'crm_contacts_base_temp', 'hs_email_last_open_date', 'STRING', 'crm_contacts_temp', 'hs_email_last_open_date', 'STRING', 20, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_hs_email_last_reply_date', 'STRING', 'crm_contacts_base_temp', 'hs_email_last_reply_date', 'STRING', 'crm_contacts_temp', 'hs_email_last_reply_date', 'STRING', 21, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_hs_email_last_send_date', 'STRING', 'crm_contacts_base_temp', 'hs_email_last_send_date', 'STRING', 'crm_contacts_temp', 'hs_email_last_send_date', 'STRING', 22, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_hs_object_id', 'STRING', 'crm_contacts_base_temp', 'hs_object_id', 'STRING', 'crm_contacts_temp', 'hs_object_id', 'STRING', 23, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_contacts', 'properties_lastmodifieddate', 'STRING', 'crm_contacts_base_temp', 'lastmodifieddate', 'STRING', 'crm_contacts_temp', 'lastmodifieddate', 'STRING', 24, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [crm_companies]  (0 transformed / 20 kept)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_companies', 'id', 'STRING', 'crm_companies_base_temp', 'company_id', 'STRING', 'crm_companies_temp', 'company_id', 'STRING', 1, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'created_at', 'STRING', 'crm_companies_base_temp', 'created_timestamp', 'STRING', 'crm_companies_temp', 'created_timestamp', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'updated_at', 'STRING', 'crm_companies_base_temp', 'updated_timestamp', 'STRING', 'crm_companies_temp', 'updated_timestamp', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'archived', 'STRING', 'crm_companies_base_temp', 'is_archived', 'STRING', 'crm_companies_temp', 'is_archived', 'INT', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'archived_at', 'STRING', 'crm_companies_base_temp', 'archived_timestamp', 'STRING', 'crm_companies_temp', 'archived_timestamp', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'object_write_trace_id', 'STRING', 'crm_companies_base_temp', 'write_trace_id', 'STRING', 'crm_companies_temp', 'write_trace_id', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'url', 'STRING', 'crm_companies_base_temp', 'record_url', 'STRING', 'crm_companies_temp', 'record_url', 'STRING', 7, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'properties_json', 'STRING', 'crm_companies_base_temp', 'properties_json', 'STRING', 'crm_companies_temp', 'properties_json', 'STRING', 8, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'properties_json_createdate', 'STRING', 'crm_companies_base_temp', 'created_timestamp', 'STRING', 'crm_companies_temp', 'created_timestamp', 'STRING', 9, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'properties_json_domain', 'STRING', 'crm_companies_base_temp', 'company_domain', 'STRING', 'crm_companies_temp', 'company_domain', 'STRING', 10, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'properties_json_hs_lastmodifieddate', 'STRING', 'crm_companies_base_temp', 'updated_timestamp', 'STRING', 'crm_companies_temp', 'updated_timestamp', 'STRING', 11, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'properties_json_hs_object_id', 'STRING', 'crm_companies_base_temp', 'company_id', 'STRING', 'crm_companies_temp', 'company_id', 'STRING', 12, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'properties_json_name', 'STRING', 'crm_companies_base_temp', 'company_name', 'STRING', 'crm_companies_temp', 'company_name', 'STRING', 13, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_companies', 'object_type', 'STRING', 'crm_companies_base_temp', 'object_type', 'STRING', 'crm_companies_temp', 'object_type', 'STRING', 14, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());
-- [crm_owners]  (11 transformed / 0 kept)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_owners', 'id', 'STRING', 'crm_owners_base_temp', 'id', 'STRING', 'crm_owners_temp', 'id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_owners', 'email', 'STRING', 'crm_owners_base_temp', 'email', 'STRING', 'crm_owners_temp', 'email', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_owners', 'firstName', 'STRING', 'crm_owners_base_temp', 'first_name', 'STRING', 'crm_owners_temp', 'first_name', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_owners', 'lastName', 'STRING', 'crm_owners_base_temp', 'last_name', 'STRING', 'crm_owners_temp', 'last_name', 'STRING', 4, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_owners', 'type', 'STRING', 'crm_owners_base_temp', 'type', 'STRING', 'crm_owners_temp', 'type', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_owners', 'userId', 'STRING', 'crm_owners_base_temp', 'user_id', 'STRING', 'crm_owners_temp', 'user_id', 'INT', 6, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_owners', 'userIdIncludingInactive', 'STRING', 'crm_owners_base_temp', 'user_id_including_inactive', 'STRING', 'crm_owners_temp', 'user_id_including_inactive', 'INT', 7, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_owners', 'createdAt', 'STRING', 'crm_owners_base_temp', 'created_at', 'STRING', 'crm_owners_temp', 'created_at', 'STRING', 8, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_owners', 'updatedAt', 'STRING', 'crm_owners_base_temp', 'updated_at', 'STRING', 'crm_owners_temp', 'updated_at', 'STRING', 9, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_owners', 'archived', 'STRING', 'crm_owners_base_temp', 'archived', 'STRING', 'crm_owners_temp', 'archived', 'BOOLEAN', 10, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_owners', 'teams', 'STRING', 'crm_owners_base_temp', 'teams', 'STRING', 'crm_owners_temp', 'teams_json', 'STRING', 11, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [marketing_email_statistics]  (64 transformed / 0 kept)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'marketing_email_statistics', 'emails', 'STRING', 'marketing_email_statistics_base_temp', 'emails', 'STRING', 'marketing_email_statistics_temp', 'email_id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_sent', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_sent', 'STRING', 'marketing_email_statistics_temp', 'cnt_sent', 'INT', 2, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_open', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_open', 'STRING', 'marketing_email_statistics_temp', 'cnt_open', 'INT', 3, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_delivered', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_delivered', 'STRING', 'marketing_email_statistics_temp', 'cnt_delivered', 'INT', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_bounce', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_bounce', 'STRING', 'marketing_email_statistics_temp', 'cnt_bounce', 'INT', 5, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_unsubscribed', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_unsubscribed', 'STRING', 'marketing_email_statistics_temp', 'cnt_unsubscribed', 'INT', 6, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_click', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_click', 'STRING', 'marketing_email_statistics_temp', 'cnt_click', 'INT', 7, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_reply', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_reply', 'STRING', 'marketing_email_statistics_temp', 'cnt_reply', 'INT', 8, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_dropped', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_dropped', 'STRING', 'marketing_email_statistics_temp', 'cnt_dropped', 'INT', 9, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_selected', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_selected', 'STRING', 'marketing_email_statistics_temp', 'cnt_selected', 'INT', 10, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_spamreport', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_spamreport', 'STRING', 'marketing_email_statistics_temp', 'cnt_spamreport', 'INT', 11, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_suppressed', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_suppressed', 'STRING', 'marketing_email_statistics_temp', 'cnt_suppressed', 'INT', 12, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_hardbounced', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_hardbounced', 'STRING', 'marketing_email_statistics_temp', 'cnt_hardbounced', 'INT', 13, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_softbounced', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_softbounced', 'STRING', 'marketing_email_statistics_temp', 'cnt_softbounced', 'INT', 14, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_pending', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_pending', 'STRING', 'marketing_email_statistics_temp', 'cnt_pending', 'INT', 15, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_contactslost', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_contactslost', 'STRING', 'marketing_email_statistics_temp', 'cnt_contactslost', 'INT', 16, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_counters_notsent', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_counters_notsent', 'STRING', 'marketing_email_statistics_temp', 'cnt_notsent', 'INT', 17, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_clickratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_clickratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_click', 'FLOAT', 18, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_clickthroughratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_clickthroughratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_clickthrough', 'FLOAT', 19, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_deliveredratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_deliveredratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_delivered', 'FLOAT', 20, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_openratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_openratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_open', 'FLOAT', 21, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_replyratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_replyratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_reply', 'FLOAT', 22, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_unsubscribedratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_unsubscribedratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_unsubscribed', 'FLOAT', 23, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_spamreportratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_spamreportratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_spamreport', 'FLOAT', 24, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_bounceratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_bounceratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_bounce', 'FLOAT', 25, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_hardbounceratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_hardbounceratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_hardbounce', 'FLOAT', 26, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_softbounceratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_softbounceratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_softbounce', 'FLOAT', 27, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_contactslostratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_contactslostratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_contactslost', 'FLOAT', 28, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_pendingratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_pendingratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_pending', 'FLOAT', 29, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_ratios_notsentratio', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_ratios_notsentratio', 'STRING', 'marketing_email_statistics_temp', 'ratio_notsent', 'FLOAT', 30, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_deviceBreakdown', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_device_breakdown', 'STRING', 'marketing_email_statistics_temp', 'device_breakdown_json', 'STRING', 31, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'aggregate_qualifierStats', 'STRING', 'marketing_email_statistics_base_temp', 'aggregate_qualifier_stats', 'STRING', 'marketing_email_statistics_temp', 'qualifier_stats_json', 'STRING', 32, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations', 'STRING', 'marketing_email_statistics_temp', 'campaign_id', 'STRING', 33, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_sent', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_sent', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_sent', 'INT', 34, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_open', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_open', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_open', 'INT', 35, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_delivered', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_delivered', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_delivered', 'INT', 36, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_bounce', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_bounce', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_bounce', 'INT', 37, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_unsubscribed', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_unsubscribed', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_unsubscribed', 'INT', 38, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_click', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_click', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_click', 'INT', 39, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_reply', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_reply', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_reply', 'INT', 40, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_dropped', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_dropped', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_dropped', 'INT', 41, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_selected', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_selected', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_selected', 'INT', 42, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_spamreport', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_spamreport', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_spamreport', 'INT', 43, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_suppressed', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_suppressed', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_suppressed', 'INT', 44, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_hardbounced', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_hardbounced', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_hardbounced', 'INT', 45, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_softbounced', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_softbounced', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_softbounced', 'INT', 46, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_pending', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_pending', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_pending', 'INT', 47, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_contactslost', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_contactslost', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_contactslost', 'INT', 48, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_counters_notsent', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_counters_notsent', 'STRING', 'marketing_email_statistics_temp', 'campaign_cnt_notsent', 'INT', 49, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_clickratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_clickratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_click', 'FLOAT', 50, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_clickthroughratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_clickthroughratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_clickthrough', 'FLOAT', 51, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_deliveredratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_deliveredratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_delivered', 'FLOAT', 52, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_openratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_openratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_open', 'FLOAT', 53, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_replyratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_replyratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_reply', 'FLOAT', 54, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_unsubscribedratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_unsubscribedratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_unsubscribed', 'FLOAT', 55, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_spamreportratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_spamreportratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_spamreport', 'FLOAT', 56, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_bounceratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_bounceratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_bounce', 'FLOAT', 57, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_hardbounceratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_hardbounceratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_hardbounce', 'FLOAT', 58, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_softbounceratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_softbounceratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_softbounce', 'FLOAT', 59, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_contactslostratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_contactslostratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_contactslost', 'FLOAT', 60, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_pendingratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_pendingratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_pending', 'FLOAT', 61, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_ratios_notsentratio', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_ratios_notsentratio', 'STRING', 'marketing_email_statistics_temp', 'campaign_ratio_notsent', 'FLOAT', 62, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_deviceBreakdown', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_device_breakdown', 'STRING', 'marketing_email_statistics_temp', 'campaign_device_breakdown_json', 'STRING', 63, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'marketing_email_statistics', 'campaignAggregations_qualifierStats', 'STRING', 'marketing_email_statistics_base_temp', 'campaign_aggregations_qualifier_stats', 'STRING', 'marketing_email_statistics_temp', 'campaign_qualifier_stats_json', 'STRING', 64, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [event_details]  (51 transformed / 0 kept)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'event_details', 'id', 'STRING', 'event_details_base_temp', 'id', 'STRING', 'event_details_temp', 'id', 'STRING', 1, 0, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'objectType', 'STRING', 'event_details_base_temp', 'object_type', 'STRING', 'event_details_temp', 'object_type', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'objectId', 'STRING', 'event_details_base_temp', 'object_id', 'STRING', 'event_details_temp', 'object_id', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'eventType', 'STRING', 'event_details_base_temp', 'event_type', 'STRING', 'event_details_temp', 'event_type', 'STRING', 4, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'occurredAt', 'STRING', 'event_details_base_temp', 'occurred_at', 'STRING', 'event_details_temp', 'occurred_at', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_base_url', 'STRING', 'event_details_base_temp', 'hs_base_url', 'STRING', 'event_details_temp', 'hs_base_url', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_url', 'STRING', 'event_details_base_temp', 'hs_url', 'STRING', 'event_details_temp', 'hs_url', 'STRING', 7, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_query_params', 'STRING', 'event_details_base_temp', 'hs_query_params', 'STRING', 'event_details_temp', 'hs_query_params', 'STRING', 8, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_canonical_url', 'STRING', 'event_details_base_temp', 'hs_canonical_url', 'STRING', 'event_details_temp', 'hs_canonical_url', 'STRING', 9, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_url_domain', 'STRING', 'event_details_base_temp', 'hs_url_domain', 'STRING', 'event_details_temp', 'hs_url_domain', 'STRING', 10, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_url_path', 'STRING', 'event_details_base_temp', 'hs_url_path', 'STRING', 'event_details_temp', 'hs_url_path', 'STRING', 11, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_analytics_normalized_page_url', 'STRING', 'event_details_base_temp', 'hs_analytics_normalized_page_url', 'STRING', 'event_details_temp', 'hs_analytics_normalized_page_url', 'STRING', 12, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_is_virtual_url', 'STRING', 'event_details_base_temp', 'hs_is_virtual_url', 'STRING', 'event_details_temp', 'hs_is_virtual_url', 'STRING', 13, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_page_id', 'STRING', 'event_details_base_temp', 'hs_page_id', 'STRING', 'event_details_temp', 'hs_page_id', 'STRING', 14, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_page_title', 'STRING', 'event_details_base_temp', 'hs_page_title', 'STRING', 'event_details_temp', 'hs_page_title', 'STRING', 15, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_title', 'STRING', 'event_details_base_temp', 'hs_title', 'STRING', 'event_details_temp', 'hs_title', 'STRING', 16, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_targeted_content_aggregation', 'STRING', 'event_details_base_temp', 'hs_targeted_content_aggregation', 'STRING', 'event_details_temp', 'hs_targeted_content_aggregation', 'STRING', 17, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_is_virtual_referrer', 'STRING', 'event_details_base_temp', 'hs_is_virtual_referrer', 'STRING', 'event_details_temp', 'hs_is_virtual_referrer', 'STRING', 18, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_is_external', 'STRING', 'event_details_base_temp', 'hs_is_external', 'STRING', 'event_details_temp', 'hs_is_external', 'STRING', 19, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_is_amp', 'STRING', 'event_details_base_temp', 'hs_is_amp', 'STRING', 'event_details_temp', 'hs_is_amp', 'STRING', 20, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_is_in_chat_view', 'STRING', 'event_details_base_temp', 'hs_is_in_chat_view', 'STRING', 'event_details_temp', 'hs_is_in_chat_view', 'STRING', 21, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_is_new_cookie', 'STRING', 'event_details_base_temp', 'hs_is_new_cookie', 'STRING', 'event_details_temp', 'hs_is_new_cookie', 'STRING', 22, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_is_contact', 'STRING', 'event_details_base_temp', 'hs_is_contact', 'STRING', 'event_details_temp', 'hs_is_contact', 'STRING', 23, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_referrer', 'STRING', 'event_details_base_temp', 'hs_referrer', 'STRING', 'event_details_temp', 'hs_referrer', 'STRING', 24, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_device_type', 'STRING', 'event_details_base_temp', 'hs_device_type', 'STRING', 'event_details_temp', 'hs_device_type', 'STRING', 25, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_device_name', 'STRING', 'event_details_base_temp', 'hs_device_name', 'STRING', 'event_details_temp', 'hs_device_name', 'STRING', 26, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_browser', 'STRING', 'event_details_base_temp', 'hs_browser', 'STRING', 'event_details_temp', 'hs_browser', 'STRING', 27, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_browser_type', 'STRING', 'event_details_base_temp', 'hs_browser_type', 'STRING', 'event_details_temp', 'hs_browser_type', 'STRING', 28, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_browser_version_major', 'STRING', 'event_details_base_temp', 'hs_browser_version_major', 'STRING', 'event_details_temp', 'hs_browser_version_major', 'STRING', 29, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_browser_fingerprint', 'STRING', 'event_details_base_temp', 'hs_browser_fingerprint', 'STRING', 'event_details_temp', 'hs_browser_fingerprint', 'STRING', 30, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_operating_system', 'STRING', 'event_details_base_temp', 'hs_operating_system', 'STRING', 'event_details_temp', 'hs_operating_system', 'STRING', 31, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_vendor', 'STRING', 'event_details_base_temp', 'hs_vendor', 'STRING', 'event_details_temp', 'hs_vendor', 'STRING', 32, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_user_agent', 'STRING', 'event_details_base_temp', 'hs_user_agent', 'STRING', 'event_details_temp', 'hs_user_agent', 'STRING', 33, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_country', 'STRING', 'event_details_base_temp', 'hs_country', 'STRING', 'event_details_temp', 'hs_country', 'STRING', 34, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_region', 'STRING', 'event_details_base_temp', 'hs_region', 'STRING', 'event_details_temp', 'hs_region', 'STRING', 35, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_qualified_region', 'STRING', 'event_details_base_temp', 'hs_qualified_region', 'STRING', 'event_details_temp', 'hs_qualified_region', 'STRING', 36, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_city', 'STRING', 'event_details_base_temp', 'hs_city', 'STRING', 'event_details_temp', 'hs_city', 'STRING', 37, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_cf_bot_score', 'STRING', 'event_details_base_temp', 'hs_cf_bot_score', 'STRING', 'event_details_temp', 'hs_cf_bot_score', 'STRING', 38, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_hash_id', 'STRING', 'event_details_base_temp', 'hs_hash_id', 'STRING', 'event_details_temp', 'hs_hash_id', 'STRING', 39, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_log_line_timestamp', 'STRING', 'event_details_base_temp', 'hs_log_line_timestamp', 'STRING', 'event_details_temp', 'hs_log_line_timestamp', 'STRING', 40, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_processed_timestamp', 'STRING', 'event_details_base_temp', 'hs_processed_timestamp', 'STRING', 'event_details_temp', 'hs_processed_timestamp', 'STRING', 41, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_visit_source', 'STRING', 'event_details_base_temp', 'hs_visit_source', 'STRING', 'event_details_temp', 'hs_visit_source', 'STRING', 42, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_visit_source_details_1', 'STRING', 'event_details_base_temp', 'hs_visit_source_details_1', 'STRING', 'event_details_temp', 'hs_visit_source_details_1', 'STRING', 43, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_visit_source_details_2', 'STRING', 'event_details_base_temp', 'hs_visit_source_details_2', 'STRING', 'event_details_temp', 'hs_visit_source_details_2', 'STRING', 44, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_utm_campaign', 'STRING', 'event_details_base_temp', 'hs_utm_campaign', 'STRING', 'event_details_temp', 'hs_utm_campaign', 'STRING', 45, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_leviathan_linked_vids', 'STRING', 'event_details_base_temp', 'hs_leviathan_linked_vids', 'STRING', 'event_details_temp', 'hs_leviathan_linked_vids', 'STRING', 46, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_company_id', 'STRING', 'event_details_base_temp', 'hs_company_id', 'STRING', 'event_details_temp', 'hs_company_id', 'STRING', 47, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_company_domain', 'STRING', 'event_details_base_temp', 'hs_company_domain', 'STRING', 'event_details_temp', 'hs_company_domain', 'STRING', 48, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_company_domain_by_association', 'STRING', 'event_details_base_temp', 'hs_company_domain_by_association', 'STRING', 'event_details_temp', 'hs_company_domain_by_association', 'STRING', 49, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_historical_contact_associatedcompanyid', 'STRING', 'event_details_base_temp', 'hs_historical_contact_associatedcompanyid', 'STRING', 'event_details_temp', 'hs_historical_contact_associatedcompanyid', 'STRING', 50, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'event_details', 'properties_hs_historical_contact_lifecyclestage', 'STRING', 'event_details_base_temp', 'hs_historical_contact_lifecyclestage', 'STRING', 'event_details_temp', 'hs_historical_contact_lifecyclestage', 'STRING', 51, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [crm_deals]  (no JSON file)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_deals', 'id', 'STRING', 'crm_deals_base_temp', 'id', 'STRING', 'crm_deals_temp', 'id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_deals', 'createdAt', 'STRING', 'crm_deals_base_temp', 'created_at', 'STRING', 'crm_deals_temp', 'created_at', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_deals', 'updatedAt', 'STRING', 'crm_deals_base_temp', 'updated_at', 'STRING', 'crm_deals_temp', 'updated_at', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_deals', 'archived', 'STRING', 'crm_deals_base_temp', 'archived', 'STRING', 'crm_deals_temp', 'archived', 'BOOLEAN', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_deals', 'archivedAt', 'STRING', 'crm_deals_base_temp', 'archived_at', 'STRING', 'crm_deals_temp', 'archived_at', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_deals', 'objectWriteTraceId', 'STRING', 'crm_deals_base_temp', 'object_write_trace_id', 'STRING', 'crm_deals_temp', 'object_write_trace_id', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_deals', 'url', 'STRING', 'crm_deals_base_temp', 'url', 'STRING', 'crm_deals_temp', 'url', 'STRING', 7, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_deals', 'properties', 'STRING', 'crm_deals_base_temp', 'properties', 'STRING', 'crm_deals_temp', 'properties_json', 'STRING', 8, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_deals', 'N/A', 'STRING', 'crm_deals_base_temp', 'N/A', 'STRING', 'crm_deals_temp', 'object_type', 'STRING', 9, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [crm_tickets]  (no JSON file)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_tickets', 'id', 'STRING', 'crm_tickets_base_temp', 'id', 'STRING', 'crm_tickets_temp', 'id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tickets', 'createdAt', 'STRING', 'crm_tickets_base_temp', 'created_at', 'STRING', 'crm_tickets_temp', 'created_at', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tickets', 'updatedAt', 'STRING', 'crm_tickets_base_temp', 'updated_at', 'STRING', 'crm_tickets_temp', 'updated_at', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tickets', 'archived', 'STRING', 'crm_tickets_base_temp', 'archived', 'STRING', 'crm_tickets_temp', 'archived', 'BOOLEAN', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tickets', 'archivedAt', 'STRING', 'crm_tickets_base_temp', 'archived_at', 'STRING', 'crm_tickets_temp', 'archived_at', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tickets', 'objectWriteTraceId', 'STRING', 'crm_tickets_base_temp', 'object_write_trace_id', 'STRING', 'crm_tickets_temp', 'object_write_trace_id', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tickets', 'url', 'STRING', 'crm_tickets_base_temp', 'url', 'STRING', 'crm_tickets_temp', 'url', 'STRING', 7, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tickets', 'properties', 'STRING', 'crm_tickets_base_temp', 'properties', 'STRING', 'crm_tickets_temp', 'properties_json', 'STRING', 8, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tickets', 'N/A', 'STRING', 'crm_tickets_base_temp', 'N/A', 'STRING', 'crm_tickets_temp', 'object_type', 'STRING', 9, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [crm_products]  (no JSON file)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_products', 'id', 'STRING', 'crm_products_base_temp', 'id', 'STRING', 'crm_products_temp', 'id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_products', 'createdAt', 'STRING', 'crm_products_base_temp', 'created_at', 'STRING', 'crm_products_temp', 'created_at', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_products', 'updatedAt', 'STRING', 'crm_products_base_temp', 'updated_at', 'STRING', 'crm_products_temp', 'updated_at', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_products', 'archived', 'STRING', 'crm_products_base_temp', 'archived', 'STRING', 'crm_products_temp', 'archived', 'BOOLEAN', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_products', 'archivedAt', 'STRING', 'crm_products_base_temp', 'archived_at', 'STRING', 'crm_products_temp', 'archived_at', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_products', 'objectWriteTraceId', 'STRING', 'crm_products_base_temp', 'object_write_trace_id', 'STRING', 'crm_products_temp', 'object_write_trace_id', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_products', 'url', 'STRING', 'crm_products_base_temp', 'url', 'STRING', 'crm_products_temp', 'url', 'STRING', 7, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_products', 'properties', 'STRING', 'crm_products_base_temp', 'properties', 'STRING', 'crm_products_temp', 'properties_json', 'STRING', 8, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_products', 'N/A', 'STRING', 'crm_products_base_temp', 'N/A', 'STRING', 'crm_products_temp', 'object_type', 'STRING', 9, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [crm_line_items]  (no JSON file)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_line_items', 'id', 'STRING', 'crm_line_items_base_temp', 'id', 'STRING', 'crm_line_items_temp', 'id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_line_items', 'createdAt', 'STRING', 'crm_line_items_base_temp', 'created_at', 'STRING', 'crm_line_items_temp', 'created_at', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_line_items', 'updatedAt', 'STRING', 'crm_line_items_base_temp', 'updated_at', 'STRING', 'crm_line_items_temp', 'updated_at', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_line_items', 'archived', 'STRING', 'crm_line_items_base_temp', 'archived', 'STRING', 'crm_line_items_temp', 'archived', 'BOOLEAN', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_line_items', 'archivedAt', 'STRING', 'crm_line_items_base_temp', 'archived_at', 'STRING', 'crm_line_items_temp', 'archived_at', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_line_items', 'objectWriteTraceId', 'STRING', 'crm_line_items_base_temp', 'object_write_trace_id', 'STRING', 'crm_line_items_temp', 'object_write_trace_id', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_line_items', 'url', 'STRING', 'crm_line_items_base_temp', 'url', 'STRING', 'crm_line_items_temp', 'url', 'STRING', 7, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_line_items', 'properties', 'STRING', 'crm_line_items_base_temp', 'properties', 'STRING', 'crm_line_items_temp', 'properties_json', 'STRING', 8, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_line_items', 'N/A', 'STRING', 'crm_line_items_base_temp', 'N/A', 'STRING', 'crm_line_items_temp', 'object_type', 'STRING', 9, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [crm_quotes]  (no JSON file)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_quotes', 'id', 'STRING', 'crm_quotes_base_temp', 'id', 'STRING', 'crm_quotes_temp', 'id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_quotes', 'createdAt', 'STRING', 'crm_quotes_base_temp', 'created_at', 'STRING', 'crm_quotes_temp', 'created_at', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_quotes', 'updatedAt', 'STRING', 'crm_quotes_base_temp', 'updated_at', 'STRING', 'crm_quotes_temp', 'updated_at', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_quotes', 'archived', 'STRING', 'crm_quotes_base_temp', 'archived', 'STRING', 'crm_quotes_temp', 'archived', 'BOOLEAN', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_quotes', 'archivedAt', 'STRING', 'crm_quotes_base_temp', 'archived_at', 'STRING', 'crm_quotes_temp', 'archived_at', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_quotes', 'objectWriteTraceId', 'STRING', 'crm_quotes_base_temp', 'object_write_trace_id', 'STRING', 'crm_quotes_temp', 'object_write_trace_id', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_quotes', 'url', 'STRING', 'crm_quotes_base_temp', 'url', 'STRING', 'crm_quotes_temp', 'url', 'STRING', 7, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_quotes', 'properties', 'STRING', 'crm_quotes_base_temp', 'properties', 'STRING', 'crm_quotes_temp', 'properties_json', 'STRING', 8, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_quotes', 'N/A', 'STRING', 'crm_quotes_base_temp', 'N/A', 'STRING', 'crm_quotes_temp', 'object_type', 'STRING', 9, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [crm_calls]  (no JSON file)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_calls', 'id', 'STRING', 'crm_calls_base_temp', 'id', 'STRING', 'crm_calls_temp', 'id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_calls', 'createdAt', 'STRING', 'crm_calls_base_temp', 'created_at', 'STRING', 'crm_calls_temp', 'created_at', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_calls', 'updatedAt', 'STRING', 'crm_calls_base_temp', 'updated_at', 'STRING', 'crm_calls_temp', 'updated_at', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_calls', 'archived', 'STRING', 'crm_calls_base_temp', 'archived', 'STRING', 'crm_calls_temp', 'archived', 'BOOLEAN', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_calls', 'archivedAt', 'STRING', 'crm_calls_base_temp', 'archived_at', 'STRING', 'crm_calls_temp', 'archived_at', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_calls', 'objectWriteTraceId', 'STRING', 'crm_calls_base_temp', 'object_write_trace_id', 'STRING', 'crm_calls_temp', 'object_write_trace_id', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_calls', 'url', 'STRING', 'crm_calls_base_temp', 'url', 'STRING', 'crm_calls_temp', 'url', 'STRING', 7, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_calls', 'properties', 'STRING', 'crm_calls_base_temp', 'properties', 'STRING', 'crm_calls_temp', 'properties_json', 'STRING', 8, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_calls', 'N/A', 'STRING', 'crm_calls_base_temp', 'N/A', 'STRING', 'crm_calls_temp', 'object_type', 'STRING', 9, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [crm_meetings]  (no JSON file)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_meetings', 'id', 'STRING', 'crm_meetings_base_temp', 'id', 'STRING', 'crm_meetings_temp', 'id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_meetings', 'createdAt', 'STRING', 'crm_meetings_base_temp', 'created_at', 'STRING', 'crm_meetings_temp', 'created_at', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_meetings', 'updatedAt', 'STRING', 'crm_meetings_base_temp', 'updated_at', 'STRING', 'crm_meetings_temp', 'updated_at', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_meetings', 'archived', 'STRING', 'crm_meetings_base_temp', 'archived', 'STRING', 'crm_meetings_temp', 'archived', 'BOOLEAN', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_meetings', 'archivedAt', 'STRING', 'crm_meetings_base_temp', 'archived_at', 'STRING', 'crm_meetings_temp', 'archived_at', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_meetings', 'objectWriteTraceId', 'STRING', 'crm_meetings_base_temp', 'object_write_trace_id', 'STRING', 'crm_meetings_temp', 'object_write_trace_id', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_meetings', 'url', 'STRING', 'crm_meetings_base_temp', 'url', 'STRING', 'crm_meetings_temp', 'url', 'STRING', 7, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_meetings', 'properties', 'STRING', 'crm_meetings_base_temp', 'properties', 'STRING', 'crm_meetings_temp', 'properties_json', 'STRING', 8, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_meetings', 'N/A', 'STRING', 'crm_meetings_base_temp', 'N/A', 'STRING', 'crm_meetings_temp', 'object_type', 'STRING', 9, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [crm_notes]  (no JSON file)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_notes', 'id', 'STRING', 'crm_notes_base_temp', 'id', 'STRING', 'crm_notes_temp', 'id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_notes', 'createdAt', 'STRING', 'crm_notes_base_temp', 'created_at', 'STRING', 'crm_notes_temp', 'created_at', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_notes', 'updatedAt', 'STRING', 'crm_notes_base_temp', 'updated_at', 'STRING', 'crm_notes_temp', 'updated_at', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_notes', 'archived', 'STRING', 'crm_notes_base_temp', 'archived', 'STRING', 'crm_notes_temp', 'archived', 'BOOLEAN', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_notes', 'archivedAt', 'STRING', 'crm_notes_base_temp', 'archived_at', 'STRING', 'crm_notes_temp', 'archived_at', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_notes', 'objectWriteTraceId', 'STRING', 'crm_notes_base_temp', 'object_write_trace_id', 'STRING', 'crm_notes_temp', 'object_write_trace_id', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_notes', 'url', 'STRING', 'crm_notes_base_temp', 'url', 'STRING', 'crm_notes_temp', 'url', 'STRING', 7, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_notes', 'properties', 'STRING', 'crm_notes_base_temp', 'properties', 'STRING', 'crm_notes_temp', 'properties_json', 'STRING', 8, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_notes', 'N/A', 'STRING', 'crm_notes_base_temp', 'N/A', 'STRING', 'crm_notes_temp', 'object_type', 'STRING', 9, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());

-- [crm_tasks]  (no JSON file)
INSERT INTO schema_config (source_name, landing_table_name, landing_column_name, landing_data_type, bronze_table_name, bronze_column_name, bronze_data_type, silver_table_name, silver_column_name, silver_data_type, ordinal_position, include_in_md5hash, is_primary_key, is_nullable, default_value, is_active, created_at)
VALUES
  ('HubSpot', 'crm_tasks', 'id', 'STRING', 'crm_tasks_base_temp', 'id', 'STRING', 'crm_tasks_temp', 'id', 'STRING', 1, 1, 1, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tasks', 'createdAt', 'STRING', 'crm_tasks_base_temp', 'created_at', 'STRING', 'crm_tasks_temp', 'created_at', 'STRING', 2, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tasks', 'updatedAt', 'STRING', 'crm_tasks_base_temp', 'updated_at', 'STRING', 'crm_tasks_temp', 'updated_at', 'STRING', 3, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tasks', 'archived', 'STRING', 'crm_tasks_base_temp', 'archived', 'STRING', 'crm_tasks_temp', 'archived', 'BOOLEAN', 4, 1, 0, 0, '0', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tasks', 'archivedAt', 'STRING', 'crm_tasks_base_temp', 'archived_at', 'STRING', 'crm_tasks_temp', 'archived_at', 'STRING', 5, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tasks', 'objectWriteTraceId', 'STRING', 'crm_tasks_base_temp', 'object_write_trace_id', 'STRING', 'crm_tasks_temp', 'object_write_trace_id', 'STRING', 6, 1, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tasks', 'url', 'STRING', 'crm_tasks_base_temp', 'url', 'STRING', 'crm_tasks_temp', 'url', 'STRING', 7, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tasks', 'properties', 'STRING', 'crm_tasks_base_temp', 'properties', 'STRING', 'crm_tasks_temp', 'properties_json', 'STRING', 8, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE()),
  ('HubSpot', 'crm_tasks', 'N/A', 'STRING', 'crm_tasks_base_temp', 'N/A', 'STRING', 'crm_tasks_temp', 'object_type', 'STRING', 9, 0, 0, 0, 'NOT_PROVIDED', 1, GETUTCDATE());
